### ISSUE TITLE
Permission methods Are changed

### ISSUE THREAD

**Issue by Aryankaushik2312** [Ronak99/Skype-Clone#10]
So please update this code. It will take 20 minutes only. I will be happy if u solve this issue as soon as possible

**Comment by takiuddin93** [comment]
> So please update this code. It will take 20 minutes only. I will be happy if u solve this issue as soon as possible

You can downgrade to previous ones to stay stable.

**Comment by Aryankaushik2312** [comment]
> > So please update this code. It will take 20 minutes only. I will be happy if u solve this issue as soon as possible
> 
> You can downgrade to previous ones to stay stable.

I already update new Permission methods. Thanks for replying

**Comment by takiuddin93** [comment]
> > > So please update this code. It will take 20 minutes only. I will be happy if u solve this issue as soon as possible
> > 
> > 
> > You can downgrade to previous ones to stay stable.
> 
> I already update new Permission methods. Thanks for replying

no, the app has issues with the new versions, permission_handler: ^3.0.0 this version works just fine.

**Comment by Ronak99** [comment]
Hope this issue was resolved. 
Either you can use the same version of the Permissions plugin in order to use the same code, 
else, use the latest version and check the changelog to see what new things have they added.

I'll probably update the code as well.

**Comment by Aryankaushik2312** [comment]
> Hope this issue was resolved.
> Either you can use the same version of the Permissions plugin in order to use the same code,
> else, use the latest version and check the changelog to see what new things have they added.
> 
> I'll probably update the code as well.

Thanks
