### ISSUE TITLE
NoSuchMethodError (NoSuchMethodError: The method '[]' was called on null. Receiver: null Tried calling: []("uid"))

### ISSUE THREAD

**Issue by clintonksang** [Ronak99/Skype-Clone#19]
![image](https://user-images.githubusercontent.com/55794066/84597790-ec298100-ae6e-11ea-88b7-48308e443ad5.png)

I cant proceed from here,  The 14th Commit

**Comment by AndreLiu1225** [comment]
@clintonksang Did you find a solution to this issue? I am facing the same bug.
