### ISSUE TITLE
Search screen not displaying anything when I search 

### ISSUE THREAD

**Issue by sharmahal** [Ronak99/Skype-Clone#23]
initially my code was working fine but after working more on the project , I got this error 
[NoSuchMethodError: The method 'where' was called on null.
Receiver: null
Tried calling: where(Closure: (User) => bool)
See also:
https://flutter.dev/docs/testing/errors]

then I changed my a funtion and wrote this - 
            `  buildSuggestions(String query) {
    final List<User> suggestionList = query.isEmpty
        ? []
        : userList != null
        ? userList.where((User user) {
      String _getUsername = user.username.toLowerCase();
      String _query = query.toLowerCase();
      String _getName = user.name.toLowerCase();
      bool matchesUsername = _getUsername.contains(_query);
      bool matchesName = _getName.contains(_query);

      return (matchesUsername || matchesName);

      // (User user) => (user.username.toLowerCase().contains(query.toLowerCase()) ||
      //     (user.name.toLowerCase().contains(query.toLowerCase()))),
    }).toList()
        : [];`

but still the search screen doesnt display the user it used to display intially

**Comment by AjayKannan97** [comment]
I am getting the same error. Did you figure it out?

**Comment by 12amansharma** [comment]
Try copying the code from the repository as it is , it will work.

**Comment by AjayKannan97** [comment]
I tried that. Still the problem persists.

**Comment by takiuddin93** [comment]
try clearing everything from database..

https://github.com/Ronak99/Skype-Clone/issues/3#issuecomment-618594117

**Comment by takiuddin93** [comment]
https://github.com/Ronak99/Skype-Clone/issues/3#issuecomment-618594117

**Comment by sharmahal** [comment]
clearing everything from database did not work for me

**Comment by sharmahal** [comment]
> try clearing everything from database..
> 
> [#3 (comment)](https://github.com/Ronak99/Skype-Clone/issues/3#issuecomment-618594117)

didnt work for me

**Comment by AjayKannan97** [comment]
W/Firestore( 9173): (21.3.0) [FirestoreCallCredentials]: **Failed to get token**: com.google.firebase.firestore.FirebaseFirestoreException: getToken aborted due to token change.

Before searching, as soon as you click the search button in the home page, I am getting this error in the terminal.

**Comment by AjayKannan97** [comment]
https://stackoverflow.com/questions/52513691/firebase-js-error-gettoken-aborted-due-to-token-change

I fixed it by modifying the database rules. 

`rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read;
      allow write;
    }
  }
}`

This should set it right.

**Comment by sharmahal** [comment]
> https://stackoverflow.com/questions/52513691/firebase-js-error-gettoken-aborted-due-to-token-change
> 
> I fixed it by modifying the database rules.
> 
> `rules_version = '2'; service cloud.firestore { match /databases/{database}/documents { match /{document=**} { allow read; allow write; } } }`
> 
> This should set it right.

This worked for me, thank you so much

**Comment by arifjawad** [comment]
> https://stackoverflow.com/questions/52513691/firebase-js-error-gettoken-aborted-due-to-token-change
> 
> I fixed it by modifying the database rules.
> 
> `rules_version = '2'; service cloud.firestore { match /databases/{database}/documents { match /{document=**} { allow read; allow write; } } }`
> 
> This should set it right.

this worked for me too, thanks
