### ISSUE TITLE
Getting an error when tried to do search for user from database

### ISSUE THREAD

**Issue by Jainish-shah** [Ronak99/Skype-Clone#3]
Recently, I cloned the Part - 6 - Search Screen UI and Functionality where I faced one error, that is occurring in the userList where the error says 

[NoSuchMethodError: The method 'toLowerCase' was called on null.
Receiver: null
Tried calling: toLowerCase()
See also: https://flutter.dev/docs/testing/errors
Below I have attached the screenshot of the error too...
![WhatsApp Image 2020-04-16 at 4 54 04 PM](https://user-images.githubusercontent.com/47889375/79454355-b3a12e80-8008-11ea-8ae6-3135bbac73a2.jpeg)

This error occurred after I changed the previous error issue code

**Comment by Ronak99** [comment]
Hey, Please take a look at this issue : 
 https://github.com/Ronak99/Skype-Clone/issues/2

I will be leaving that issue open, to make it visible to everyone, whereas I'll be closing this one.

Please feel free to open an issue, if you find a bug in the future.

**Comment by Jainish-shah** [comment]
It's not working I tried it...

**Comment by Ronak99** [comment]
> Hey, Please take a look at this issue :
> #2
> 
> I will be leaving that issue open, to make it visible to everyone, whereas I'll be closing this one.
> 
> Please feel free to open an issue, if you find a bug in the future.

Never Mind, I might have confused this issue, with the previous one. I just realised that this is different, I am opening it again.

**Comment by Ronak99** [comment]
I might have to look into your code. Please link the repository, so that I can take a look.

**Comment by Jainish-shah** [comment]
https://github.com/Jainish-shah/Skype_clone

**Comment by takiuddin93** [comment]
> https://github.com/Jainish-shah/Skype_clone

I cloned your repo and tried it. I don't see this issue with the same code. I haven't made any changes to your configurations. 

could be silly but try:
1. flutter clean
2. delete your users collections from database and login fresh.

**Comment by Ronak99** [comment]
Hey @Jainish-shah, I hope the solution suggested by @takiuddin93 worked for you.
It would be great if you could follow up on the status of that issue.
Thanks.

**Comment by Jainish-shah** [comment]
Thanks @takiuddin93 and @Ronak99 for helping I got the solution by deleting all the user collections from the database
