### ISSUE TITLE
How to get call duration minutes between two users ?

### ISSUE THREAD

**Issue by maheshperi19** [Ronak99/Skype-Clone#33]
Hi,

Thanks for this example project with agora sdk. I want some suggestions to solve my requirements.

1) How to get call duration in minutes between two users?
     As you are saving timestamp that is call starting time.

2) How to make voice call ? Already i tried by disable video. But it didn't work.
 AgoraRtcEngine.disableVideo();

3) It would be great if provide pickup layout when app is in background mode/close/kill mode.

4) Incoming ringtone while second user is receiving a call.

**Comment by maheshperi19** [comment]
1) How to get call duration in minutes between two users?

agora provided as agora analytics rest api which is paid plan. It provides all the data.

2) How to make voice call ? Already i tried by disable video. But it didn't work.
AgoraRtcEngine.disableVideo();

AgoraRtcEngine.muteLocalVideoStream(true); Works fine.

4) Incoming ringtone while second user is receiving a call.
   For this i used this package : flutter_ringtone_player: ^2.0.0

I need help on my 3rd question. Please any one can suggest me how to do this. 

When the app is in background mode, and if call is receiving, need to awake the app to foreground or need to notify user like stream push.

**Comment by hasnainsaeed9692** [comment]
@MaheshPeri19 Did you implement the background mode? Please share some code if you have I badly need it

**Comment by maheshperi19** [comment]
No. With this example, only working for foreground. So that i used Awesome Notifications package for action buttons on notifications. 

https://pub.dev/packages/awesome_notifications

But i need incoming call notification instead of message notification. So that i just modified as per below comment link. 

https://github.com/rafaelsetragni/awesome_notifications/issues/35#issuecomment-751431492

Please check it.

But unfortunately, it will work only for Android, not for iOS. I just found below link for flutter incoming calls (i dont know about this). Please have a look.

https://github.com/Alezhka/flutter_incoming_call
