### ISSUE TITLE
The following NoSuchMethodError was thrown during a scheduler callback:

### ISSUE THREAD

**Issue by prakashssp077** [Ronak99/Skype-Clone#4]
The getter 'uid' was called on null.
Receiver: null
Tried calling: uid

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _HomeScreenState.initState.<anonymous closure> (package:skypeclone/screens/home_screen.dart:33:38)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
#4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
...

**Comment by prakashssp077** [comment]
![1](https://user-images.githubusercontent.com/55954247/79722714-2dcffc80-8302-11ea-9f70-c5a13d05ca60.png)

**Comment by takiuddin93** [comment]
is your code for getUserDetails in auth_methods fine? also this is thrown when you are in homescreen?

**Comment by prakashssp077** [comment]
Yes

**Comment by prakashssp077** [comment]
![3](https://user-images.githubusercontent.com/55954247/79726572-a33ecb80-8308-11ea-9791-62c9831182e5.png)

**Comment by takiuddin93** [comment]
the problem you are facing seems to be here in auth_methods

Future<User> getUserDetails() async {
    FirebaseUser currentUser = await getCurrentUser();

    DocumentSnapshot documentSnapshot =
        await _userCollection.document(currentUser.uid).get();

    return User.fromMap(documentSnapshot.data);
  }

however, make sure your manifest has uses-permissions for internet. do print in all possible fetch calls.

kind of similar issue as #3 but his code has no issue on my side.

**Comment by prakashssp077** [comment]
![4](https://user-images.githubusercontent.com/55954247/79729956-c455eb00-830d-11ea-824c-7bb1a9857b07.png)

**Comment by prakashssp077** [comment]
i am getting this type of exceptions

**Comment by takiuddin93** [comment]
try pulling my repo and see if the problem still exists, your repo is in private, can't try it on my machine.

**Comment by Ronak99** [comment]
Hey @prakashssp077, hope your issue got resolved, it would be really helpful if you drop a link to your repo so anyone can fork it and try to reproduce the issue.

Also, thanks @takiuddin93 for helping the community. I appreciate it.
