### ISSUE TITLE
Did anyone implement the calling feature when app is closed or fone is locked ?

### ISSUE THREAD

**Issue by hasnainsaeed9692** [Ronak99/Skype-Clone#46]
Hi everyone
Can anybody tell me how to implement the calling feature when the app is closed or fone is locked? I've tried many methods but couldn't implement it . Please share some code if you have done this.
Thanks

**Comment by Ronak99** [comment]
Hey, that functionality is implementable but not just in Flutter. You should start looking into time-sensitive notifications in Android and work your way forward in that direction.
