### ISSUE TITLE
when I  pressed end call button, stream is not returning scaffold

### ISSUE THREAD

**Issue by omerrciftcii** [Ronak99/Skype-Clone#5]
Hello, I have problem with on call end. When I press end call, records deleting succesfully from collection but stream is not returning scaffold

**Comment by Ronak99** [comment]
I am assuming that you are on branch 12, if so, please try pulling the code of the next branch and compare the code, you might be missing something.

If that does not help, then it would be helpful if you link the repo here, so that I can take a look.

**Comment by omerrciftcii** [comment]
> I am assuming that you are on branch 12, if so, please try pulling the code of the next branch and compare the code, you might be missing something.
> 
> If that does not help, then it would be helpful if you link the repo here, so that I can take a look.

Issue has been solved, it is my mistake, thanks for quick reply
