### ISSUE TITLE
After Final Build App not opening

### ISSUE THREAD

**Issue by pnirav996** [Ronak99/Skype-Clone#7]
Below error message in mobile

`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.chatbee/com.example.chatbee.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.chatbee.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/lib/arm64, /data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2876)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.chatbee.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/lib/arm64, /data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1216)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
	... 11 more`

**Comment by AhsanHameed97** [comment]
facing same issue just screen stay on login text

**Comment by moshTech** [comment]
Here too

**Comment by moshTech** [comment]
Click on that login text to perform login

**Comment by takiuddin93** [comment]
> Below error message in mobile
> 
> `java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.chatbee/com.example.chatbee.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.chatbee.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/lib/arm64, /data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk!/lib/arm64-v8a, /system/lib64]] at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2876) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:201) at android.app.ActivityThread.main(ActivityThread.java:6823) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.chatbee.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/lib/arm64, /data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk!/lib/arm64-v8a, /system/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69) at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43) at android.app.Instrumentation.newActivity(Instrumentation.java:1216) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864) ... 11 more`

your android files are alright?

**Comment by pnirav996** [comment]
> > Below error message in mobile
> > 
> > `java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.chatbee/com.example.chatbee.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.chatbee.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/lib/arm64, /data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk!/lib/arm64-v8a, /system/lib64]] at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2876) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:201) at android.app.ActivityThread.main(ActivityThread.java:6823) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.chatbee.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/lib/arm64, /data/app/com.example.chatbee-E19D9G7k3x6AXtBZL8pcrg==/base.apk!/lib/arm64-v8a, /system/lib64]] at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171) at java.lang.ClassLoader.loadClass(ClassLoader.java:379) at java.lang.ClassLoader.loadClass(ClassLoader.java:312) at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69) at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43) at android.app.Instrumentation.newActivity(Instrumentation.java:1216) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864) ... 11 more`
> 
> your android files are alright?

Yes bro.

**Comment by takiuddin93** [comment]
is it possible to see your repository?

**Comment by pnirav996** [comment]
Thanks. Error is gone.

**Comment by takiuddin93** [comment]
> Thanks. Error is gone.

what was the issue and what fixed it?

**Comment by pnirav996** [comment]
> > Thanks. Error is gone.
> 
> what was the issue and what fixed it?

Just in issue in min SDK & targeted SDK
